---
- hosts: "proxmox_servers"
  become: yes
  gather_facts: yes
  roles:
    - proxmox-provision
    - proxmox-notification

# This reboot task should probably go inside the proxmox-provision role.
# In order to make testing easier on me, I have it here.
- hosts: "proxmox_servers"
  become: yes
  gather_facts: yes
  tasks:
    - name: Reboot Proxmox Host
      reboot:
        reboot_timeout: 3600

- hosts: "proxmox_template_host"
  become: yes
  gather_facts: yes
  roles:
    - proxmox-cloud-init-template

- hosts: "proxmox_vms"
  become: yes
  gather_facts: no
  roles:
    - proxmox-vm-buildout
  
- hosts: "proxmox_vms"
  become: yes
  gather_facts: yes
  tasks:
    - name: Reboot Virtual Machines
      reboot:
        reboot_timeout: 3600

- hosts: "docker_hosts"
  become: true
  gather_facts: true
  roles:
    - geerlingguy.docker
    - docker-provision